<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Meet-Loc : Annonce logement</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <h1>Collocation</h1>
        <div class=
        <button type="button"><a href="accueil.phtml">Retour</a></button>
        
    </body>

</html>

